# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # node version
    strategy:
      matrix:
        node-version: ['16.15']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # setup node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # install npm packages
      - name: install npm packages
        run: |
          npm ci

      # check type
      - name: check type
        run: |
          npm run check-type
          
      # check build
      - name: check build
        run: |
          npm run build

      # check test
      - name: test
        run: |
          npm run test
